### PR TITLE
change skip to a variable

### PR DESCRIPTION
**Pull request by pdietl**
Parameterizing the skip variable is needed for my use of a makeself file.

### CODE REVIEW

**Comment by woky** [comment]
What's your use?

**Comment by pdietl** [comment]
@woky I need this change for a use case of makeself that we are using at ADTRAN.
We are taking the approach of generating the self-extracting file (AKA SEF), and then signing it with an external tool. We do this by appending the signature to the end of the sef.

The idea is that we cannot rely on the script on the front of the tarball to not be malicious, and so we must verify the entire SEF. 

To do this, we need to be able to grep,sed certain variables out of the script in front of the tarball. Once such variable that we need is the skip varaiable, in order to determine the end of the sef and the beginning of the signature.

**Comment by megastep** [comment]
If you can't implicitly trust the script at the beginning of the file, while would you trust anything you extract from it?

**Comment by megastep** [comment]
If I understand you correctly, you don't want to run any code from the archive until you've properly validated its signature, and this makes it easy to extract the number of lines to skip?

**Comment by pdietl** [comment]
Correct!

**Comment by pdietl** [comment]
If any of the attempts to sed values out of the script header fail in any way or don't make sense relative to the size of the file, then we fail.

**Comment by megastep** [comment]
Ok, then I see how that can be useful. Thanks!

**Pull request merged**
