### PR TITLE
Added threading support

### PR DESCRIPTION
**Pull request by mlimber**
Fulfilling issue described in [issue 203](https://github.com/megastep/makeself/issues/203).

### CODE REVIEW

**Comment by megastep** [comment]
This is interesting, but my main concern is specifying these threads arguments to commands that will then be invoked by the archive. It seems to me that it would make such archives more prone to fail to extract on systems where the `xz` command for instance isn't compiled with threading support.

**Comment by megastep** [comment]
Also the benefits of these I would think are fairly minimal for most systems, and would only have a small performance improvement for massive archives (where I/O tends to be a bigger bottleneck anyway). So I'm not convinced potentially breaking the universality of archives is a good trade-off.

**Comment by megastep** [comment]
Nevermind, looks like I misread the code and was thinking of decompression more than compression 😅

**Comment by mlimber** [comment]
Thanks. I upped the version number to 2.4.2. Do you want to create a release tag for it? (Note: the version log at the top of the main `.sh` file didn't have an entry for 2.4.1.)

**Comment by megastep** [comment]
Probably soon. There's a few other issues that might warrant another look first.

**Pull request merged**
