### PR TITLE
move from bashunit to shunit2. refactoring tests.

### PR DESCRIPTION
**Pull request by hemnstill**
bashunit → shunit2 [47be8b23a46a](https://github.com/kward/shunit2/commits/47be8b23a46a7897e849f1841f0fb704d34d0f6e) for better maintainability
replace assertEqual → assertEquals
skip unstable test `datetest.testByteforbyte` (sometimes fails on any os)

move run-tests.sh to ./test dir

`run-testlinter.sh` for test headers consistency (THIS, THISDIR)

simplify `build.yml`. add matrix strategy to build on alpine alongside with other os.

move from ubuntu-latest to ubuntu:latest in docker for more transparency regarding dependencies

makeself sources have not been changed.

### CODE REVIEW

**Comment by realtime-neil** [comment]
I have been waiting for this day.

**Comment by realtime-neil** [comment]
@hemnstill wait, why are you not doing this with a submodule?

**Comment by megastep** [comment]
Thanks a lot for this, it looks great! I also wonder if we really need to copy the shunit2 code in the repo though, I'd really much prefer to have it as a submodule or something similar.

**Comment by hemnstill** [comment]
Sumbodules needs more attention to start working with repo. 

I personally prefer not to use them, but let the submodules remain.

add submodules.

**Pull request merged**
