### PR TITLE
Try to ensure the script passed is executable

### PR DESCRIPTION
**Pull request by pbor**
Try to mark the script as executable and if that fails report an error

### CODE REVIEW

**Comment by megastep** [comment]
The problem is that the script is not necessarily a file name, it could just be any command, in which case `chmod` would fail in any case. For instance, I often have the script as something like "sh setup.sh".

**Comment by pbor** [comment]
I see... I updated the PR to first check if script is an actual script file and only in that case try to make it executable

**Comment by pbor** [comment]
Sorry for pinging, but the quick response to the initial PR spoiled me :)

Do you see any problems in the updated patch?

**Comment by megastep** [comment]
I'm still kinda debating whether I think it's a good idea or not. I'm generally not a fan of explicitly changing permissions of files provided by the user in the first place. Is there a use case where this is really necessary, i.e. one where you can't specify a command as part of the script (i.e. call bash, perl, etc if it comes down to it).

The main case I can think where this would be the case is if you actually include a compiled binary, but even then since it's a bundled file you don't need to worry about permissions since they should be preserved in the archive.

**Comment by pbor** [comment]
I'll check with my colleagues, we have been carrying that patch for a while and I do not recall exactly under which conditions it was needed.

I think we had some bug reports from customers where the problem happened, but I need to dig out why... maybe it was fixed now that makeself is more careful with preserving permissions. Or maybe it happened when extracting to a FS with specific mount options: if that was the case at least the patch would report a meaningful error

**Comment by pbor** [comment]
I thought some more about this and decided that it is indeed better to simpy pass "/bin/bash ./install.sh" to makeself, so that it will work even for some reason install.sh is not +x.

I am closing this PR and dropping my fork of makeself since we can now just use the upstream version.

Maybe it would still be useful to have something like

+		if test -f "\$script" -a ! -x "\$script"; then
+			echo >&2
+			echo "Cannot make \$script file executable" >&2
+			eval \$finish; exit 1
+		fi

Just to provide a nicer error if one does pass a script file and it is not executable.

**Pull request closed without merging**
