### PR TITLE
New option '--tar-quietly'

### PR DESCRIPTION
**Pull request by ymattw**

### CODE REVIEW

**Comment by megastep** [comment]
How is this different from just using `--quiet`?

**Comment by ymattw** [comment]
`--quiet` suppress anything, include the useful summary, while `--tar-quietly` just remove the `v` option for tar.  Adding a new option is the safest way to solve this, in terms of keep it backward compatible.

```
% ./makeself.sh --tar-quietly ../profiles  /tmp/1.bin 'test tar quietly' echo 'hello world'
Header is 507 lines long

About to compress 3488 KB of data...
Adding files to archive named "/tmp/1.bin"...
CRC: 2708470227
MD5: 80cf012bea8a85a36655d02a6f93bea9

Self-extractable archive "/tmp/1.bin" successfully created.
```

**Comment by megastep** [comment]
I understand that's what you're trying to do, however looking at your changes it doesn't seem to do anything differently than just setting `--quiet` ?

**Comment by ymattw** [comment]
I want to see the summary only, not the verbose output from tar `cvf`, currently the `v` flag is set by default and can only be unset with `--quiet`, but that will hide all output (except warning and errors).

```
% ./makeself.sh --quiet ../profiles  /tmp/1.bin 'test tar quietly' echo 'hello world'
WARNING: Overwriting existing file: /tmp/1.bin
```

**Comment by ymattw** [comment]
That said, `v` flag should not be set by default, and when user want to see verbose tar output, use `--tar-extra -v` instead.  But making such change is not backward compatible.

**Comment by megastep** [comment]
But that's just not what your code does. The only relevant piece is this:

`if test "$QUIET" = "y" || test "$TAR_QUIETLY" = "y"; then`

Which pretty much does the code path identical whether you use `--quiet` or `--tar-quietly`. I don't think your code actually does what you say it does.

**Comment by ymattw** [comment]
Well.. my tests verified it does :)

The original code is somehow confusing, when `--quiet` is set it reset `tar cvf` to `tar cf`, my change is to make the same logic also apply to `--tar-quietly`.

```
% ./makeself.sh . /tmp/1.bin 'test tar quietly' echo 'hello world'
Header is 506 lines long

WARNING: Overwriting existing file: /tmp/1.bin
About to compress 668 KB of data...
Adding files to archive named "/tmp/1.bin"...
./
./makeself-header.sh
./.git/
...
./COPYING
./makeself.sh
./makeself.lsm
./README.md
CRC: 98969665
MD5: 7e3eb8e860836d89bbb48be5289f0ed4

Self-extractable archive "/tmp/1.bin" successfully created.

% ./makeself.sh --quiet . /tmp/1.bin 'test tar quietly' echo 'hello world'
WARNING: Overwriting existing file: /tmp/1.bin

% ./makeself.sh --tar-quietly . /tmp/1.bin 'test tar quietly' echo 'hello world'
Header is 507 lines long

WARNING: Overwriting existing file: /tmp/1.bin
About to compress 668 KB of data...
Adding files to archive named "/tmp/1.bin"...
CRC: 252226991
MD5: 9950d88ca7ea73776b19b79e0b95c169

Self-extractable archive "/tmp/1.bin" successfully created.
```

**Comment by megastep** [comment]
Are you sure you haven't forgotten to commit some code to this pull request? There's no way this would happen with what's in here now. As is, there should be no distinction between using `--quiet` or `--tar-quietly`.

**Comment by megastep** [comment]
OK, maybe I have spoken too soon, as indeed the `$QUIET` variable is referenced later on, so in effect you are really just disabling the tar options here.

**Comment by megastep** [comment]
Alright, sorry about that, I should have looked at the whole file before commenting, the diff was just being a bit misleading. ;)

**Comment by ymattw** [comment]
You got it, `test "$QUIET" = "y"` is being used in multiple places but only one is related to `tar cvf`.

**Pull request merged**
